### ISSUE TITLE
bug: Addon pod complains it can't find the /var/run/secrets/eks.amazonaws.com/serviceaccount/token

### ISSUE THREAD

**Issue by brajshoriegzon** [aws/eks-node-monitoring-agent#23]
**What happened**:
On aws-nma managed addon versions v1.4.0 and above the following happens:

The addon gets installed. Pods begin running with no issues. If you check the logs of the pods you can see the following:

```
{"level":"error","ts":"2025-11-03T19:11:51Z","msg":"failed to report managed conditions","hostname":"xxx",

"error":"failed to get server groups: Get \"https://xxx.gr7.eu-central-1.eks.amazonaws.com/api\": getting credentials: exec: executable /opt/amazon/bin/chroot failed with exit code 2","stacktrace":"golang.a2z.com/EKSNodeMonitoringAgent/internal/manager.(*nodeExporter).run\n\t/local/p4clients/pkgbuild-const/workspace/src/EKSNodeMonitoringAgent/internal/manager/node_exporter.go:150\ngolang.a2z.com/EKSNodeMonitoringAgent/internal/manager.(*nodeExporter).Run\n\t/local/p4clients/pkgbuild-const/workspace/src/EKSNodeMonitoringAgent/internal/manager/node_exporter.go:137"}
{"level":"info","ts":"2025-11-03T19:12:02Z","msg":"reporting managed conditions","hostname":"xxx"}

[Errno 2] No such file or directory: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token'
panic: exit status 255
```

The issue does NOT happen in v1.3.0 and below, it has shown up in v1.4.0 and above

**What you expected to happen**:
The pods should be able to communicate with the Cluster API and should be able to find the token it requires

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**: ?
- AWS Region: eu-central-1
- Instance Type(s): m6a.large and t3.medium
- Cluster Kubernetes version: 1.31/1.32/1.33
- Node Kubernetes version:  1.31/1.32/1.33
- EKS Node Monitoring Agent version: v1.4.0 and bove

**Comment by drgivanov** [comment]
@brajshoriegzon 
Thank you for the information, unfortunately AWS has remove version 1.3.0  for my cluster so we will have to wait for fix in some of the next. 
ws eks describe-addon-versions \
  --region me-central-1 \
  --addon-name eks-node-monitoring-agent \
  --kubernetes-version 1.34 \
  --query 'addons[0].addonVersions[].addonVersion' \
  --output text
v1.5.1-eksbuild.1       v1.5.0-eksbuild.1       v1.4.3-eksbuild.2       v1.4.2-eksbuild.1       v1.4.1-eksbuild.1       v1.4.0-eksbuild.2

**Comment by brajshoriegzon** [comment]
@drgivanov 

Have you tested versions 1.5.x though?

I'm hoping the issue has been fixed in later versions

**Comment by Sefiris** [comment]
> [@brajshoriegzon](https://github.com/brajshoriegzon) [@drgivanov](https://github.com/drgivanov) do you mind sharing:
> 
> 1. The AMI you are using
> 2. The kubelet config (which is typically located in a place like `cat /var/lib/kubelet/kubeconfig`). Wanted to check the args passed to `user.name=kubelet` section.

Replying for @brajshoriegzon since we work together, tested this on add on version `v1.5.2-eksbuild.1` on an EKS cluster `1.33`, still occuring with the same error

```
│ eks-node-monitoring-agent-7r5jm goroutine 1 [running]:                                                                                                                                                                                │
│ eks-node-monitoring-agent-7r5jm main.main()                                                                                                                                                                                           │
│ eks-node-monitoring-agent-7r5jm     /local/p4clients/pkgbuild-const/workspace/src/EKSNodeMonitoringAgent/cmd/chroot/main.go:17 +0xfe                                                                                                  │
│ eks-node-monitoring-agent-7r5jm {"level":"error","ts":"2026-03-03T10:55:08Z","msg":"failed to report managed conditions","hostname":"ip-172-16-200-140.eu-central-1.compute.internal","error":"failed to get server groups: Get \"htt │
│ eks-node-monitoring-agent-zgwlr {"level":"info","ts":"2026-03-03T10:55:11Z","msg":"reporting managed conditions","hostname":"ip-172-16-223-104.eu-central-1.compute.internal"}                                                        │
│ eks-node-monitoring-agent-zgwlr could not get token: operation error STS: GetCallerIdentity, get identity: get credentials: failed to refresh cached credentials, failed to retrieve jwt from provide source, unable to read file at  │
│ eks-node-monitoring-agent-zgwlr panic: exit status 1
```

The AMI we are currently using is the latest `BOTTLEROCKET_x86_64`, but this was a recent switch for us and this same error occurred on AMI type `AL2023_X86_64`

The kubelet config is not something we edit, we use managed nodegroups without any custom launch templating
